/* ============================================================
   BEK TOUR — i18n Translations
   RU / EN / UZ
   ============================================================ */

window.I18N = {

  ru: {
    // Navbar
    nav_home:     'Главная',
    nav_dest:     'Направления',
    nav_tours:    'Туры',
    nav_hotels:   'Отели',
    nav_about:    'О нас',
    nav_contacts: 'Контакты',
    nav_b2b:      'B2B',
    nav_search_ph:'Самарканд, тур на 7 дней...',

    // Mega menu destinations
    nav_samarkand:  'Самарканд',
    nav_bukhara:    'Бухара',
    nav_khiva:      'Хива',
    nav_tashkent:   'Ташкент',
    nav_fergana:    'Ферганская долина',
    nav_all_dest:   'Все направления',

    // Mega menu tours
    nav_silk:    'Шёлковый путь',
    nav_luxury:  'Luxury туры',
    nav_nature:  'Природа',
    nav_city:    'Городские',
    nav_custom:  'Индивидуальные',

    // Mobile nav
    mob_partner: 'B2B Партнёр',
    mob_become:  'Стать партнёром',

    // Ticker
    tick1: 'Самарканд — Жемчужина Шёлкового Пути · Объект ЮНЕСКО',
    tick2: 'Бухара — 2500 лет истории и легендарный минарет Калон',
    tick3: 'Хива — Ичан-Кала · Первый объект ЮНЕСКО в Узбекистане',
    tick4: 'Безвизовый въезд для 90+ стран',
    tick5: 'Bek Tour — Лицензированный туроператор с 1999 года',

    // Hero slide 1
    h1_eyebrow: 'Шёлковый Путь · Узбекистан · UNESCO',
    h1_title1: 'Откройте',
    h1_title2: 'Душу',
    h1_title3: 'Самарканда',
    h1_sub:    'Жемчужина Востока с 2500-летней историей',
    h1_desc:   'Регистан, мечеть Биби-Ханым, мавзолей Гур-Эмир — легендарные памятники архитектуры в сердце Шёлкового Пути.',
    h1_btn1:   'Самарканд',
    h1_btn2:   'Все туры',

    // Hero slide 2
    h2_eyebrow: 'Священный город · 140 памятников · UNESCO',
    h2_title1: 'Бухара —',
    h2_title2: 'Сердце',
    h2_title3: 'Востока',
    h2_sub:    '2500 лет непрерывной истории',
    h2_desc:   'Минарет Калон, которым восхитился Чингисхан. Мечети, медресе и бесконечные лабиринты старого города.',
    h2_btn1:   'Бухара',
    h2_btn2:   'Забронировать',

    // Hero slide 3
    h3_eyebrow: 'Ичан-Кала · Первый UNESCO Узбекистана · X век',
    h3_title1: 'Хива —',
    h3_title2: 'Живой',
    h3_title3: 'Музей',
    h3_sub:    'Средневековый город-крепость без изменений',
    h3_desc:   'Единственный в мире полностью сохранившийся средневековый восточный город. Шагни в X век прямо сейчас.',
    h3_btn1:   'Хива',
    h3_btn2:   'Подобрать тур',

    // Hero stats
    stat_tourists: 'Туристов',
    stat_routes:   'Маршрутов',
    stat_rating:   'Рейтинг',
    stat_years:    'Лет',

    // Hero right card
    card_title:   '🗺 Популярные маршруты',
    card1_name:   'Золотое кольцо',
    card1_sub:    'Самарканд · Бухара · Хива',
    card1_badge:  '10 дней',
    card2_name:   'Luxury Silk Road',
    card2_sub:    'Весь Узбекистан · 5★',
    card2_badge:  '14 дней',
    card3_name:   'Природа Узбекистана',
    card3_sub:    'Чарвак · Чимган · Аральское',
    card3_badge:  '7 дней',

    // Destinations section
    sec_dest_label: 'Направления',
    sec_dest_title1: 'Исследуйте',
    sec_dest_title2: 'Узбекистан',
    dest_all: 'Все направления →',
    dest_samarkand_sub: 'Жемчужина Шёлкового Пути',
    dest_bukhara_sub:   'Священный Город',
    dest_khiva_sub:     'Музей под открытым небом',
    dest_tashkent_sub:  'Современная Столица',
    dest_fergana_sub:   'Шёлк и ремёсла',

    // Tours section
    sec_tours_label: 'Туры',
    sec_tours_title1: 'Популярные',
    sec_tours_title2: 'маршруты',
    tours_all: 'Все туры →',
    tour1_dest:  'Самарканд · Бухара · Хива',
    tour1_name:  'Золотое кольцо Узбекистана',
    tour1_badge: 'Хит',
    tour2_dest:  'Весь Узбекистан · 5★',
    tour2_name:  'Luxury Silk Road — Полный Узбекистан',
    tour2_badge: 'Эксклюзив',
    tour3_dest:  'Чарвак · Чимган · Аральское',
    tour3_name:  'Природа Узбекистана',
    tour3_badge: 'Новый',
    tour4_dest:  'Ташкент · Самарканд',
    tour4_name:  'Ташкент + Самарканд за выходные',
    tour4_badge: 'Популярный',
    days: 'дней', guests: 'чел.', from: 'от', per_person: '/чел.',
    btn_more: 'Подробнее',

    // Why section
    sec_why_label:  'Почему Узбекистан',
    sec_why_title1: 'Страна которая',
    sec_why_title2: 'удивит',
    sec_why_title3: 'вас',
    sec_why_desc:   'Узбекистан — одно из самых недооценённых направлений в мире. Безопаснее Европы. Доступнее Азии.',
    why1_title: '7 объектов ЮНЕСКО',
    why1_desc:  'Регистан, Ичан-Кала, Бухара, Шахрисабз — шедевры мировой архитектуры',
    why2_title: 'Безопасная страна',
    why2_desc:  'Один из самых низких уровней преступности в регионе',
    why3_title: 'Безвизовый въезд',
    why3_desc:  'Гражданам 90+ стран не нужна виза — приезжайте прямо сейчас',
    why4_title: 'Легендарная кухня',
    why4_desc:  'Плов, самса, лагман, шурпа — гастрономия которую невозможно забыть',

    // Hotels section
    sec_hotels_label: 'Отели',
    sec_hotels_title1: 'Лучшие',
    sec_hotels_title2: 'Отели',
    sec_hotels_title3: 'Узбекистана',
    hotels_all: 'Все отели →',
    per_night: '/ночь',
    btn_book: 'Забронировать',

    // Calculator
    sec_calc_label:  'Калькулятор',
    sec_calc_title1: 'Рассчитайте стоимость',
    sec_calc_title2: 'вашего тура',
    sec_calc_desc:   'Укажите параметры и получите предварительную стоимость за несколько секунд',
    calc_route:   'Маршрут',
    calc_days:    'Количество дней',
    calc_guests:  'Туристов',
    calc_hotel:   'Категория отеля',
    calc_currency:'Валюта',
    calc_extras:  'Дополнительные услуги',
    calc_transfer:'Трансфер',
    calc_guide:   'Гид',
    calc_visa:    'Визовая поддержка',
    calc_meals:   'Питание',
    calc_photo:   'Фотограф',
    calc_car:     'Аренда авто',
    calc_total_label: 'Предварительная стоимость',
    calc_note:    'Точная цена формируется после консультации',
    calc_btn1:    'Узнать цену',
    calc_btn2:    'Написать',

    // Tour options
    opt_silk:    'Шёлковый путь (3 города)',
    opt_city:    'Один город',
    opt_nature:  'Природа Узбекистана',
    opt_luxury:  'Luxury (весь Узбекистан)',
    opt_3d: '3 дня', opt_5d: '5 дней', opt_7d: '7 дней', opt_10d: '10 дней', opt_14d: '14 дней',
    opt_1p: '1 турист', opt_2p: '2 туриста', opt_4p: '4 туриста', opt_6p: '6 туристов',
    opt_3s: '3 звезды', opt_4s: '4 звезды', opt_5s: '5 звёзд',

    // Reviews
    sec_rev_label:  'Отзывы',
    sec_rev_title1: 'Что говорят',
    sec_rev_title2: 'туристы',

    // FAQ
    sec_faq_label:  'FAQ',
    sec_faq_title1: 'Часто задаваемые',
    sec_faq_title2: 'вопросы',
    faq1_q: 'Нужна ли виза для поездки в Узбекистан?',
    faq1_a: 'Гражданам более 90 стран не нужна виза — Россия, СНГ, большинство ЕС, США, Великобритания, Япония. Срок пребывания — 30 дней. Для остальных — e-visa за 2–3 рабочих дня.',
    faq2_q: 'Когда лучше ехать в Узбекистан?',
    faq2_a: 'Лучшее время — весна (март–май) и осень (сентябрь–ноябрь). Летом до +42°C, зимой холодно. Октябрь — сезон граната, базары особенно красочные.',
    faq3_q: 'Что входит в стоимость тура?',
    faq3_a: 'Проживание, внутренние трансферы, русскоязычный гид, входные билеты, завтраки. Авиаперелёт и страховка — дополнительно. Доступно "всё включено".',
    faq4_q: 'Какая валюта используется?',
    faq4_a: 'Узбекский сум. Доллары и евро широко принимаются в туристических зонах. Рекомендуем везти наличные доллары — выгодный курс обмена.',

    // B2B section
    sec_b2b_label:  'B2B Партнёрам',
    sec_b2b_title1: 'Присоединяйтесь к',
    sec_b2b_title2: 'экосистеме',
    sec_b2b_desc:   'Турагентства, отельеры, гиды — добавляйте объекты, управляйте бронированиями, получайте клиентов.',
    b2b_feat1: 'Бесплатная регистрация за 2 минуты',
    b2b_feat2: 'Личный кабинет — объекты, фото, бронирования',
    b2b_feat3: 'Загрузка фото через ImageKit CDN',
    b2b_feat4: 'Аналитика и отчёты в реальном времени',
    b2b_btn1:  'Стать партнёром',
    b2b_btn2:  'Подробнее',
    b2b_reg:   'Регистрация',
    b2b_act:   'Активация',
    b2b_props: 'Объектов',
    b2b_comm:  'Комиссия',

    // Newsletter
    sec_nl_label: 'Рассылка',
    nl_title:  'Специальные предложения',
    nl_desc:   'Подпишитесь и получайте эксклюзивные скидки и новые маршруты первыми',
    nl_ph:     'ваш@email.com',
    nl_btn:    'Подписаться',

    // Footer
    footer_tagline: 'Премиальный туризм в Узбекистане. Более 25 лет открываем Шёлковый путь для туристов со всего мира.',
    footer_dest:    'Направления',
    footer_tours:   'Туры и услуги',
    footer_contacts:'Контакты',
    footer_copy:    '© 2024 Bek Tour. Все права защищены.',
    footer_privacy: 'Политика конфиденциальности',
    footer_terms:   'Условия использования',

    // Tabbar
    tab_home:  'Главная',
    tab_places:'Места',
    tab_tours: 'Туры',
    tab_hotels:'Отели',
    tab_b2b:   'B2B',
  },

  en: {
    nav_home:     'Home',
    nav_dest:     'Destinations',
    nav_tours:    'Tours',
    nav_hotels:   'Hotels',
    nav_about:    'About',
    nav_contacts: 'Contact',
    nav_b2b:      'B2B',
    nav_search_ph:'Samarkand, 7-day tour...',
    nav_samarkand:  'Samarkand',
    nav_bukhara:    'Bukhara',
    nav_khiva:      'Khiva',
    nav_tashkent:   'Tashkent',
    nav_fergana:    'Fergana Valley',
    nav_all_dest:   'All destinations',
    nav_silk:    'Silk Road',
    nav_luxury:  'Luxury Tours',
    nav_nature:  'Nature',
    nav_city:    'City Tours',
    nav_custom:  'Custom Tours',
    mob_partner: 'B2B Partner',
    mob_become:  'Become a Partner',

    tick1: 'Samarkand — Pearl of the Silk Road · UNESCO',
    tick2: 'Bukhara — 2500 years of history and the legendary Kalon Minaret',
    tick3: 'Khiva — Ichan Kala · First UNESCO site in Uzbekistan',
    tick4: 'Visa-free entry for 90+ countries',
    tick5: 'Bek Tour — Licensed tour operator since 1999',

    h1_eyebrow: 'Silk Road · Uzbekistan · UNESCO',
    h1_title1: 'Discover',
    h1_title2: 'the Soul',
    h1_title3: 'of Samarkand',
    h1_sub:    'Pearl of the East with 2500 years of history',
    h1_desc:   'Registan, Bibi-Khanym Mosque, Gur-e-Amir — legendary architectural masterpieces at the heart of the Silk Road.',
    h1_btn1:   'Samarkand',
    h1_btn2:   'All Tours',

    h2_eyebrow: 'Sacred City · 140 Monuments · UNESCO',
    h2_title1: 'Bukhara —',
    h2_title2: 'Heart',
    h2_title3: 'of the East',
    h2_sub:    '2500 years of unbroken history',
    h2_desc:   'The Kalon Minaret that amazed Genghis Khan. Mosques, madrasas and endless labyrinths of the old city.',
    h2_btn1:   'Bukhara',
    h2_btn2:   'Book Now',

    h3_eyebrow: 'Ichan Kala · First UNESCO in Uzbekistan · 10th century',
    h3_title1: 'Khiva —',
    h3_title2: 'Living',
    h3_title3: 'Museum',
    h3_sub:    'Medieval fortress city unchanged through centuries',
    h3_desc:   'The world\'s only fully preserved medieval Eastern city. Step into the 10th century right now.',
    h3_btn1:   'Khiva',
    h3_btn2:   'Find a Tour',

    stat_tourists: 'Tourists',
    stat_routes:   'Routes',
    stat_rating:   'Rating',
    stat_years:    'Years',

    card_title:   '🗺 Popular Routes',
    card1_name:   'Golden Ring',
    card1_sub:    'Samarkand · Bukhara · Khiva',
    card1_badge:  '10 days',
    card2_name:   'Luxury Silk Road',
    card2_sub:    'All Uzbekistan · 5★',
    card2_badge:  '14 days',
    card3_name:   'Nature of Uzbekistan',
    card3_sub:    'Charvak · Chimgan · Aral Sea',
    card3_badge:  '7 days',

    sec_dest_label: 'Destinations',
    sec_dest_title1: 'Explore',
    sec_dest_title2: 'Uzbekistan',
    dest_all: 'All destinations →',
    dest_samarkand_sub: 'Pearl of the Silk Road',
    dest_bukhara_sub:   'Sacred City',
    dest_khiva_sub:     'Open-air Museum',
    dest_tashkent_sub:  'Modern Capital',
    dest_fergana_sub:   'Silk & Crafts',

    sec_tours_label: 'Tours',
    sec_tours_title1: 'Popular',
    sec_tours_title2: 'Routes',
    tours_all: 'All tours →',
    tour1_dest:  'Samarkand · Bukhara · Khiva',
    tour1_name:  'Golden Ring of Uzbekistan',
    tour1_badge: 'Bestseller',
    tour2_dest:  'All Uzbekistan · 5★',
    tour2_name:  'Luxury Silk Road — Full Uzbekistan',
    tour2_badge: 'Exclusive',
    tour3_dest:  'Charvak · Chimgan · Aral Sea',
    tour3_name:  'Nature of Uzbekistan',
    tour3_badge: 'New',
    tour4_dest:  'Tashkent · Samarkand',
    tour4_name:  'Tashkent + Samarkand Weekend',
    tour4_badge: 'Popular',
    days: 'days', guests: 'pax', from: 'from', per_person: '/person',
    btn_more: 'Details',

    sec_why_label:  'Why Uzbekistan',
    sec_why_title1: 'A country that will',
    sec_why_title2: 'amaze',
    sec_why_title3: 'you',
    sec_why_desc:   'Uzbekistan is one of the most underrated destinations in the world. Safer than Europe. More affordable than Asia.',
    why1_title: '7 UNESCO Sites',
    why1_desc:  'Registan, Ichan Kala, Bukhara, Shahrisabz — masterpieces of world architecture',
    why2_title: 'Safe Country',
    why2_desc:  'One of the lowest crime rates in the region. Tourists feel completely safe',
    why3_title: 'Visa-Free Entry',
    why3_desc:  'Citizens of 90+ countries need no visa — come right now',
    why4_title: 'Legendary Cuisine',
    why4_desc:  'Plov, samsa, lagman, shurpa — gastronomy you will never forget',

    sec_hotels_label: 'Hotels',
    sec_hotels_title1: 'Best',
    sec_hotels_title2: 'Hotels',
    sec_hotels_title3: 'in Uzbekistan',
    hotels_all: 'All hotels →',
    per_night: '/night',
    btn_book: 'Book Now',

    sec_calc_label:  'Calculator',
    sec_calc_title1: 'Calculate the cost of',
    sec_calc_title2: 'your tour',
    sec_calc_desc:   'Enter your preferences and get a preliminary price in seconds',
    calc_route:   'Route',
    calc_days:    'Number of days',
    calc_guests:  'Tourists',
    calc_hotel:   'Hotel category',
    calc_currency:'Currency',
    calc_extras:  'Additional services',
    calc_transfer:'Transfer',
    calc_guide:   'Guide',
    calc_visa:    'Visa support',
    calc_meals:   'Meals',
    calc_photo:   'Photographer',
    calc_car:     'Car rental',
    calc_total_label: 'Preliminary cost',
    calc_note:    'Exact price is formed after consultation',
    calc_btn1:    'Get Price',
    calc_btn2:    'Contact Us',

    opt_silk:    'Silk Road (3 cities)',
    opt_city:    'One city',
    opt_nature:  'Nature of Uzbekistan',
    opt_luxury:  'Luxury (all Uzbekistan)',
    opt_3d: '3 days', opt_5d: '5 days', opt_7d: '7 days', opt_10d: '10 days', opt_14d: '14 days',
    opt_1p: '1 tourist', opt_2p: '2 tourists', opt_4p: '4 tourists', opt_6p: '6 tourists',
    opt_3s: '3 stars', opt_4s: '4 stars', opt_5s: '5 stars',

    sec_rev_label:  'Reviews',
    sec_rev_title1: 'What',
    sec_rev_title2: 'travelers say',

    sec_faq_label:  'FAQ',
    sec_faq_title1: 'Frequently Asked',
    sec_faq_title2: 'Questions',
    faq1_q: 'Do I need a visa to visit Uzbekistan?',
    faq1_a: 'Citizens of 90+ countries don\'t need a visa — Russia, CIS, most EU, USA, UK, Japan. Stay up to 30 days. Others can get e-visa in 2–3 business days.',
    faq2_q: 'When is the best time to visit Uzbekistan?',
    faq2_a: 'Best time is spring (March–May) and autumn (September–November). Summer can reach +42°C. October is pomegranate season with colorful bazaars.',
    faq3_q: 'What is included in the tour price?',
    faq3_a: 'Accommodation, internal transfers, English-speaking guide, entrance tickets, breakfasts. International flights and insurance are extra. All-inclusive available.',
    faq4_q: 'What currency is used?',
    faq4_a: 'Uzbekistani som. USD and EUR widely accepted in tourist areas. We recommend bringing cash dollars — excellent exchange rates.',

    sec_b2b_label:  'For Partners',
    sec_b2b_title1: 'Join our',
    sec_b2b_title2: 'ecosystem',
    sec_b2b_desc:   'Travel agencies, hotels, guides — list your properties, manage bookings, get clients.',
    b2b_feat1: 'Free registration in 2 minutes',
    b2b_feat2: 'Personal dashboard — properties, photos, bookings',
    b2b_feat3: 'Photo upload via ImageKit CDN',
    b2b_feat4: 'Real-time analytics and reports',
    b2b_btn1:  'Become a Partner',
    b2b_btn2:  'Learn More',
    b2b_reg:   'Registration',
    b2b_act:   'Activation',
    b2b_props: 'Properties',
    b2b_comm:  'Commission',

    sec_nl_label: 'Newsletter',
    nl_title:  'Special Offers',
    nl_desc:   'Subscribe and be the first to receive exclusive deals and new routes',
    nl_ph:     'your@email.com',
    nl_btn:    'Subscribe',

    footer_tagline: 'Premium tourism in Uzbekistan. Over 25 years opening the Silk Road to travelers from around the world.',
    footer_dest:    'Destinations',
    footer_tours:   'Tours & Services',
    footer_contacts:'Contact',
    footer_copy:    '© 2024 Bek Tour. All rights reserved.',
    footer_privacy: 'Privacy Policy',
    footer_terms:   'Terms of Use',

    tab_home:  'Home',
    tab_places:'Places',
    tab_tours: 'Tours',
    tab_hotels:'Hotels',
    tab_b2b:   'B2B',
  },

  uz: {
    nav_home:     'Bosh sahifa',
    nav_dest:     'Yo\'nalishlar',
    nav_tours:    'Turlar',
    nav_hotels:   'Mehmonxonalar',
    nav_about:    'Biz haqimizda',
    nav_contacts: 'Aloqa',
    nav_b2b:      'B2B',
    nav_search_ph:'Samarqand, 7 kunlik tur...',
    nav_samarkand:  'Samarqand',
    nav_bukhara:    'Buxoro',
    nav_khiva:      'Xiva',
    nav_tashkent:   'Toshkent',
    nav_fergana:    'Farg\'ona vodiysi',
    nav_all_dest:   'Barcha yo\'nalishlar',
    nav_silk:    'Ipak yo\'li',
    nav_luxury:  'Luxury turlar',
    nav_nature:  'Tabiat',
    nav_city:    'Shahar turlari',
    nav_custom:  'Individual turlar',
    mob_partner: 'B2B Hamkor',
    mob_become:  'Hamkor bo\'lish',

    tick1: 'Samarqand — Ipak Yo\'li gavhari · UNESCO',
    tick2: 'Buxoro — 2500 yillik tarix va Kalon minorasi',
    tick3: 'Xiva — Ichan Qal\'a · O\'zbekistondagi birinchi UNESCO',
    tick4: '90+ mamlakat uchun vizasiz kirish',
    tick5: 'Bek Tour — 1999 yildan litsenziyalangan tur operatori',

    h1_eyebrow: 'Ipak Yo\'li · O\'zbekiston · UNESCO',
    h1_title1: 'Samarqandning',
    h1_title2: 'Ruhini',
    h1_title3: 'Kashf Eting',
    h1_sub:    '2500 yillik tarixga ega Sharq gavhari',
    h1_desc:   'Registon, Bibixonim masjidi, G\'ur Amir maqbarasi — Ipak yo\'li markazidagi me\'moriy durdonalar.',
    h1_btn1:   'Samarqand',
    h1_btn2:   'Barcha turlar',

    h2_eyebrow: 'Muqaddas shahar · 140 yodgorlik · UNESCO',
    h2_title1: 'Buxoro —',
    h2_title2: 'Sharqning',
    h2_title3: 'Qalbi',
    h2_sub:    '2500 yillik uzluksiz tarix',
    h2_desc:   'Chingizxonni hayratga solgan Kalon minorasi. Masjidlar, madrasalar va eski shaharning cheksiz labirintlari.',
    h2_btn1:   'Buxoro',
    h2_btn2:   'Bron qilish',

    h3_eyebrow: 'Ichan Qal\'a · O\'zbekistondagi birinchi UNESCO · X asr',
    h3_title1: 'Xiva —',
    h3_title2: 'Tirik',
    h3_title3: 'Muzey',
    h3_sub:    'O\'rta asrlar qal\'a-shahri o\'zgarishsiz',
    h3_desc:   'Dunyodagi yagona to\'liq saqlanib qolgan o\'rta asrlar sharq shahri. Hoziroq X asrga qadaming.',
    h3_btn1:   'Xiva',
    h3_btn2:   'Tur tanlash',

    stat_tourists: 'Sayyohlar',
    stat_routes:   'Marshrutlar',
    stat_rating:   'Reyting',
    stat_years:    'Yil',

    card_title:   '🗺 Mashhur marshrutlar',
    card1_name:   'Oltin halqa',
    card1_sub:    'Samarqand · Buxoro · Xiva',
    card1_badge:  '10 kun',
    card2_name:   'Luxury Ipak Yo\'li',
    card2_sub:    'Butun O\'zbekiston · 5★',
    card2_badge:  '14 kun',
    card3_name:   'O\'zbekiston tabiati',
    card3_sub:    'Charvak · Chimyon · Orol',
    card3_badge:  '7 kun',

    sec_dest_label: 'Yo\'nalishlar',
    sec_dest_title1: 'O\'zbekistonni',
    sec_dest_title2: 'Kashf Eting',
    dest_all: 'Barcha yo\'nalishlar →',
    dest_samarkand_sub: 'Ipak Yo\'li gavhari',
    dest_bukhara_sub:   'Muqaddas shahar',
    dest_khiva_sub:     'Ochiq havoli muzey',
    dest_tashkent_sub:  'Zamonaviy poytaxt',
    dest_fergana_sub:   'Ipak va hunarmandchilik',

    sec_tours_label: 'Turlar',
    sec_tours_title1: 'Mashhur',
    sec_tours_title2: 'marshrutlar',
    tours_all: 'Barcha turlar →',
    tour1_dest:  'Samarqand · Buxoro · Xiva',
    tour1_name:  'O\'zbekiston Oltin Halqasi',
    tour1_badge: 'Hit',
    tour2_dest:  'Butun O\'zbekiston · 5★',
    tour2_name:  'Luxury Ipak Yo\'li — To\'liq O\'zbekiston',
    tour2_badge: 'Eksklyuziv',
    tour3_dest:  'Charvak · Chimyon · Orol',
    tour3_name:  'O\'zbekiston tabiati',
    tour3_badge: 'Yangi',
    tour4_dest:  'Toshkent · Samarqand',
    tour4_name:  'Toshkent + Samarqand dam olish kunlari',
    tour4_badge: 'Mashhur',
    days: 'kun', guests: 'kishi', from: 'dan', per_person: '/kishi',
    btn_more: 'Batafsil',

    sec_why_label:  'Nima uchun O\'zbekiston',
    sec_why_title1: 'Sizni',
    sec_why_title2: 'hayratga',
    sec_why_title3: 'soladigan mamlakat',
    sec_why_desc:   'O\'zbekiston dunyodagi eng kam baholangan yo\'nalishlardan biri. Yevropadan xavfsizroq. Osiyodan arzonroq.',
    why1_title: '7 ta UNESCO ob\'ekti',
    why1_desc:  'Registon, Ichan Qal\'a, Buxoro, Shahrisabz — jahon me\'morchiligining durdonalari',
    why2_title: 'Xavfsiz mamlakat',
    why2_desc:  'Mintaqadagi eng past jinoyatchilik darajalaridan biri',
    why3_title: 'Vizasiz kirish',
    why3_desc:  '90+ mamlakat fuqarolari uchun viza kerak emas',
    why4_title: 'Afsonaviy oshxona',
    why4_desc:  'Palov, somsa, lag\'mon, sho\'rva — unutib bo\'lmaydigan ta\'mlar',

    sec_hotels_label: 'Mehmonxonalar',
    sec_hotels_title1: 'O\'zbekistonning',
    sec_hotels_title2: 'Eng Yaxshi',
    sec_hotels_title3: 'Mehmonxonalari',
    hotels_all: 'Barcha mehmonxonalar →',
    per_night: '/kecha',
    btn_book: 'Bron qilish',

    sec_calc_label:  'Kalkulyator',
    sec_calc_title1: 'Turingiz narxini',
    sec_calc_title2: 'hisoblang',
    sec_calc_desc:   'Parametrlarni kiriting va bir necha soniyada taxminiy narxni oling',
    calc_route:   'Marshrut',
    calc_days:    'Kunlar soni',
    calc_guests:  'Sayyohlar',
    calc_hotel:   'Mehmonxona toifasi',
    calc_currency:'Valyuta',
    calc_extras:  'Qo\'shimcha xizmatlar',
    calc_transfer:'Transfer',
    calc_guide:   'Gid',
    calc_visa:    'Viza yordami',
    calc_meals:   'Ovqatlanish',
    calc_photo:   'Fotograf',
    calc_car:     'Avtomobil ijarasi',
    calc_total_label: 'Taxminiy narx',
    calc_note:    'Aniq narx maslahatdan so\'ng aniqlanadi',
    calc_btn1:    'Narxni bilish',
    calc_btn2:    'Yozish',

    opt_silk:    'Ipak yo\'li (3 shahar)',
    opt_city:    'Bitta shahar',
    opt_nature:  'O\'zbekiston tabiati',
    opt_luxury:  'Luxury (butun O\'zbekiston)',
    opt_3d: '3 kun', opt_5d: '5 kun', opt_7d: '7 kun', opt_10d: '10 kun', opt_14d: '14 kun',
    opt_1p: '1 sayyoh', opt_2p: '2 sayyoh', opt_4p: '4 sayyoh', opt_6p: '6 sayyoh',
    opt_3s: '3 yulduz', opt_4s: '4 yulduz', opt_5s: '5 yulduz',

    sec_rev_label:  'Sharhlar',
    sec_rev_title1: 'Sayyohlar',
    sec_rev_title2: 'nima deydi',

    sec_faq_label:  'FAQ',
    sec_faq_title1: 'Ko\'p so\'raladigan',
    sec_faq_title2: 'savollar',
    faq1_q: 'O\'zbekistonga viza kerakmi?',
    faq1_a: '90+ mamlakat fuqarolari uchun viza kerak emas — Rossiya, MDH, ko\'pchilik EU, AQSh, Britaniya, Yaponiya. 30 kungacha qolish. Qolganlari uchun e-viza 2–3 ish kunida.',
    faq2_q: 'O\'zbekistonga qachon borish yaxshi?',
    faq2_a: 'Eng yaxshi vaqt — bahor (mart–may) va kuz (sentyabr–noyabr). Yozda +42°C gacha. Oktyabr — anor fasli, bozorlar ayniqsa rang-barang.',
    faq3_q: 'Tur narxiga nima kiradi?',
    faq3_a: 'Turar joy, ichki transferlar, o\'zbekistonlik gid, kirish chiptalari, nonushtalar. Xalqaro parvoz va sug\'urta alohida. "Hammasi kiritilgan" varianti mavjud.',
    faq4_q: 'Qanday valyuta ishlatiladi?',
    faq4_a: 'O\'zbek so\'mi. Dollar va evro turistik hududlarda keng qabul qilinadi. Naqd dollar olib borish tavsiya etiladi — qulay almashtirish kursi.',

    sec_b2b_label:  'Hamkorlar uchun',
    sec_b2b_title1: 'Ekotizimga',
    sec_b2b_title2: 'qo\'shiling',
    sec_b2b_desc:   'Tur agentliklari, mehmonxonalar, gidlar — ob\'ektlar qo\'shing, bronlarni boshqaring, mijozlar oling.',
    b2b_feat1: '2 daqiqada bepul ro\'yxatdan o\'tish',
    b2b_feat2: 'Shaxsiy kabinet — ob\'ektlar, rasmlar, bronlar',
    b2b_feat3: 'ImageKit CDN orqali rasm yuklash',
    b2b_feat4: 'Real vaqtda tahlil va hisobotlar',
    b2b_btn1:  'Hamkor bo\'lish',
    b2b_btn2:  'Batafsil',
    b2b_reg:   'Ro\'yxatdan o\'tish',
    b2b_act:   'Faollashtirish',
    b2b_props: 'Ob\'ektlar',
    b2b_comm:  'Komissiya',

    sec_nl_label: 'Xabarnoma',
    nl_title:  'Maxsus takliflar',
    nl_desc:   'Obuna bo\'ling va eksklyuziv chegirmalar va yangi marshrutlarni birinchilar qatorida oling',
    nl_ph:     'sizning@email.com',
    nl_btn:    'Obuna bo\'lish',

    footer_tagline: 'O\'zbekistonda premium turizm. 25 yildan ortiq dunyo bo\'ylab sayyohlar uchun Ipak yo\'lini ochamiz.',
    footer_dest:    'Yo\'nalishlar',
    footer_tours:   'Turlar va xizmatlar',
    footer_contacts:'Aloqa',
    footer_copy:    '© 2024 Bek Tour. Barcha huquqlar himoyalangan.',
    footer_privacy: 'Maxfiylik siyosati',
    footer_terms:   'Foydalanish shartlari',

    tab_home:  'Bosh sahifa',
    tab_places:'Joylar',
    tab_tours: 'Turlar',
    tab_hotels:'Mehmonxona',
    tab_b2b:   'B2B',
  },
};
